"""
sa-framework builders — command-line entry point.

    python build.py <engagement-dir> [--type offer|estimation-pack|all]
                                     [--version NN] [--pdf] [--dry-run]
                                     [--out DIR] [--json]

This is what `/sa:package` runs. The command resolves the slug, checks the gates and reports the
result; **everything between reading the JSON and writing the files happens here**, in code that is
the same on every run.

That split is the point. Packaging used to be a prose specification the model re-implemented each
time, which cost thousands of tokens per run and produced a different document each time: a
workbook missing a whole tab, a cover and an information table disagreeing about the version, an
internal "do not edit this file by hand" note shipped to a client. Those are not reasoning
failures. Deterministic work belongs in deterministic code.

Exit status is 0 on a successful build even when there are findings — findings are reported, not
fatal. A non-zero status means no usable deliverable was produced.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import profiles  # noqa: E402
from common import load_json, load_json_optional  # noqa: E402
from estimation_xlsx import WorkbookBuilder  # noqa: E402
from offer_docx import OfferBuilder  # noqa: E402
from validate import validate  # noqa: E402

ARTIFACT_FILES = {
    "engagement": "engagement.json",
    "requirements": "requirements.json",
    "architecture": "architecture.json",
    "detailed_design": "detailed-design.json",
    "risk_register": "risk-register.json",
    "estimation": "estimation.json",
    "offer": "offer.json",
}

TYPE_REQUIREMENTS = {
    "offer": ["engagement", "offer"],
    "estimation-pack": ["engagement", "estimation"],
}


def load_artifacts(engagement_dir: Path):
    """Read every artifact that exists. Absent ones are None; the caller decides if that matters."""
    artifacts = {}
    for key, filename in ARTIFACT_FILES.items():
        artifacts[key] = load_json_optional(engagement_dir / filename)
    if artifacts["engagement"] is None:
        raise FileNotFoundError(
            f"No engagement.json in {engagement_dir}. Run /sa:triage first — without it there is "
            "no lane, no client and no document profile."
        )
    return artifacts


def next_version(out_dir: Path, artifact: str, explicit=None):
    """Resolve the version number for this build.

    Scans existing deliverables for `-<artifact>-v<NN>` and returns the next one. A versioned
    deliverable is never overwritten: a document that has been sent is a fact about the past.
    """
    if explicit:
        return f"{int(explicit):02d}"
    highest = 0
    if out_dir.is_dir():
        pattern = re.compile(rf"-{re.escape(artifact)}-v(\d+)\.", re.I)
        for path in out_dir.iterdir():
            match = pattern.search(path.name)
            if match:
                highest = max(highest, int(match.group(1)))
    return f"{highest + 1:02d}"


def document_ref(engagement, document_profile, report=None):
    """Resolve the engagement's document reference, e.g. GEO-2026-VodafoneRO-001.

    An explicit `document_ref` in engagement.json always wins; it is the reference already quoted
    in emails and on earlier versions, and regenerating it would silently renumber a live bid.

    When there is none the reference is composed from the org's `doc_id_prefix`, the year, the
    client name and `001`, and the fact that it was composed is reported. Composing silently is
    how a second offer to the same client acquires the same number as the first.
    """
    explicit = engagement.get("document_ref")
    if explicit:
        return explicit, False
    org_prefix = (
        (document_profile.get("org") or {}).get("doc_id_prefix")
        or engagement.get("doc_id_prefix")
        or "DOC"
    )
    client = re.sub(r"[^A-Za-z0-9]", "", engagement.get("client") or "Client")
    ref = f"{org_prefix}-{date.today().year}-{client}-001"
    if report is not None:
        report["findings"].append(
            f"engagement.json has no `document_ref`, so '{ref}' was composed for this build. "
            "Set it explicitly in engagement.json so consecutive versions keep one reference."
        )
    return ref, True


def filename_for(engagement, artifact, version, extension, ref):
    """Build the deliverable filename from the engagement's own naming convention."""
    template = engagement.get("file_naming") or "<ORG>-<YYYY>-<CLIENT>-<NNN>-<artifact>-v<NN>.<ext>"
    match = re.match(r"^([A-Za-z]+)-(\d{4})-([A-Za-z0-9]+)-(\d+)$", ref or "")
    if match:
        org, year, client, number = match.groups()
    else:
        org = "DOC"
        year = str(date.today().year)
        client = re.sub(r"[^A-Za-z0-9]", "", engagement.get("client") or "Client")
        number = "001"
    return (
        template.replace("<ORG>", org)
        .replace("<YYYY>", year)
        .replace("<CLIENT>", client)
        .replace("<NNN>", number)
        .replace("<artifact>", artifact)
        .replace("<NN>", version)
        .replace("<ext>", extension)
    )


def build(engagement_dir, types, version=None, want_pdf=False, out_dir=None, dry_run=False):
    """Build the requested deliverables. Returns a machine-readable report."""
    engagement_dir = Path(engagement_dir).resolve()
    artifacts = load_artifacts(engagement_dir)
    engagement = artifacts["engagement"]
    out_dir = Path(out_dir) if out_dir else engagement_dir / "deliverables"

    render_profile = profiles.resolve_render_profile(engagement)
    document_profile = profiles.resolve_document_profile(engagement)

    report = {
        "engagement_dir": str(engagement_dir),
        "render_profile": render_profile["_resolved"],
        "redundant_profile_overrides": render_profile.get("_redundant_overrides") or [],
        "document_profile": {
            "branded": document_profile["branded"],
            "reason": document_profile["reason"],
            "template": str(document_profile.get("template_path") or ""),
            "profile": (document_profile.get("profile") or {}).get("key"),
        },
        "built": [],
        "findings": [],
        "errors": [],
    }

    mismatch = profiles.check_language_match(engagement, document_profile)
    if mismatch:
        report["errors"].append(mismatch)
        return report

    if not document_profile["branded"]:
        report["findings"].append(
            f"UNBRANDED build: {document_profile['reason']}. "
            "The client will not see their branding on any DOCX produced by this run."
        )

    ref, _composed = document_ref(engagement, document_profile, report)
    report["document_ref"] = ref

    # Preflight. Catching a malformed artifact here costs milliseconds; catching it after a build
    # costs a document that looks finished and is wrong.
    errors, warnings = validate(artifacts, types)
    report["findings"].extend(warnings)
    if errors:
        report["errors"].extend(errors)
        return report

    for artifact_type in types:
        missing = [
            key for key in TYPE_REQUIREMENTS.get(artifact_type, [])
            if artifacts.get(key) is None
        ]
        if missing:
            report["errors"].append(
                f"Cannot build '{artifact_type}': missing "
                + ", ".join(ARTIFACT_FILES[k] for k in missing)
            )
            continue

        try:
            if artifact_type == "offer":
                _build_offer(artifacts, render_profile, document_profile, out_dir,
                             version, want_pdf, dry_run, report, engagement, ref)
            elif artifact_type == "estimation-pack":
                _build_workbook(artifacts, render_profile, out_dir, version, dry_run,
                                report, engagement, ref)
            else:
                report["errors"].append(f"Unknown deliverable type '{artifact_type}'.")
        except Exception as exc:  # noqa: BLE001 — one failed type must not lose the others
            report["errors"].append(f"{artifact_type}: {type(exc).__name__}: {exc}")

    return report


def _build_offer(artifacts, render_profile, document_profile, out_dir, version, want_pdf,
                 dry_run, report, engagement, ref):
    resolved = next_version(out_dir, "offer", version)
    name = filename_for(engagement, "offer", resolved, "docx", ref)
    builder = OfferBuilder(artifacts, render_profile, document_profile, out_dir, resolved)
    if dry_run:
        report["built"].append({"type": "offer", "path": str(out_dir / name), "dry_run": True})
        return
    path = builder.build(out_dir / name)
    entry = {
        "type": "offer",
        "path": str(path),
        "version": resolved,
        "size_kb": round(path.stat().st_size / 1024, 1),
    }
    report["findings"].extend(f"offer: {f}" for f in builder.findings)

    # The table-of-contents field is inert until Word computes it. Say so exactly once, and only
    # when it is actually still inert — a warning that fires after the field was refreshed teaches
    # the reader to ignore the warning.
    if builder.toc_added and not want_pdf:
        report["findings"].append(
            "offer: the table of contents is an unpopulated Word field. Pass --pdf to have Word "
            "compute it, or open the DOCX and accept the update-fields prompt."
        )

    if want_pdf:
        import pdf as pdf_module

        result = pdf_module.refresh_and_export(path, path.with_suffix(".pdf"))
        entry["pdf"] = result.get("pdf")
        entry["fields_refreshed"] = result.get("fields_refreshed")
        entry["pdf_route"] = result.get("route")
        if result.get("note"):
            report["findings"].append(f"offer PDF: {result['note']}")
        if not result.get("fields_refreshed"):
            report["findings"].append(
                "offer: the table of contents is still an unpopulated Word field. "
                "Open the DOCX in Word and accept the update-fields prompt."
            )
    report["built"].append(entry)


def _build_workbook(artifacts, render_profile, out_dir, version, dry_run, report, engagement, ref):
    resolved = next_version(out_dir, "estimation", version)
    name = filename_for(engagement, "estimation", resolved, "xlsx", ref)
    builder = WorkbookBuilder(artifacts, render_profile)
    if dry_run:
        report["built"].append({"type": "estimation-pack", "path": str(out_dir / name), "dry_run": True})
        return
    path = builder.build(out_dir / name)
    report["findings"].extend(f"estimation-pack: {f}" for f in builder.findings)
    report["built"].append({
        "type": "estimation-pack",
        "path": str(path),
        "version": resolved,
        "size_kb": round(path.stat().st_size / 1024, 1),
        "sheets": builder.wb.sheetnames,
    })


def main(argv=None):
    # Windows consoles default to a legacy code page, so an em dash or an arrow in a finding kills
    # the run after the files are already on disk — the build succeeds and the report crashes.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    parser = argparse.ArgumentParser(description="Build SA client deliverables from JSON artifacts.")
    parser.add_argument("engagement_dir", help="ai/sa/<slug>/ directory")
    parser.add_argument("--type", default="all",
                        help="offer | estimation-pack | all (default: all)")
    parser.add_argument("--version", help="force a version number, e.g. 03")
    parser.add_argument("--pdf", action="store_true",
                        help="also export a PDF, refreshing the table-of-contents field")
    parser.add_argument("--out", help="output directory (default: <engagement-dir>/deliverables)")
    parser.add_argument("--dry-run", action="store_true",
                        help="resolve profiles and report what would be built, writing nothing")
    parser.add_argument("--json", action="store_true", help="machine-readable report on stdout")
    args = parser.parse_args(argv)

    types = ["offer", "estimation-pack"] if args.type == "all" else [args.type]
    report = build(args.engagement_dir, types, args.version, args.pdf, args.out, args.dry_run)

    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        _print_report(report)
    return 1 if (report["errors"] or not report["built"]) else 0


def _print_report(report):
    profile = report["render_profile"]
    print(f"Render profile : {profile['name']}  ({profile['reason']})")
    doc = report["document_profile"]
    print(f"Document shell : {'branded — ' + str(doc['profile']) if doc['branded'] else 'UNBRANDED'}"
          f"  ({doc['reason']})")
    if report["redundant_profile_overrides"]:
        print(f"  note: profile keys restating an inherited value: "
              f"{', '.join(report['redundant_profile_overrides'])}")
    print()
    for entry in report["built"]:
        extra = ""
        if entry.get("sheets"):
            extra = f"  [{len(entry['sheets'])} sheets: {', '.join(entry['sheets'])}]"
        if entry.get("pdf"):
            extra += f"\n                 + PDF via {entry.get('pdf_route')}" \
                     f" (fields refreshed: {entry.get('fields_refreshed')})"
        print(f"BUILT  {entry['type']:<16} v{entry.get('version', '?')}  "
              f"{entry.get('size_kb', '?')} KB  {entry['path']}{extra}")
    if report["findings"]:
        print("\nFindings (reported, not fatal):")
        for finding in report["findings"]:
            print(f"  - {finding}")
    if report["errors"]:
        print("\nERRORS:")
        for error in report["errors"]:
            print(f"  ! {error}")


if __name__ == "__main__":
    raise SystemExit(main())
