"""
sa-framework builders — client-facing offer DOCX.

Turns an engagement's JSON artifacts into the document a client reads. Deterministic: the same
artifacts and the same render profile always produce the same document.

**Why this is code and not a prompt.** `/sa:package` used to describe this document in prose and
have the model write a build script each run. Three defects in one shipped offer show why that
does not hold: the cover said version 9.0 while the Document Information table said 1.0, the body
opened with "Generated from offer.json revision 9. Do not edit this file by hand.", and the
workbook beside it had lost a whole tab the specification called for. None of those are reasoning
failures. They are what happens when a deterministic rendering job is re-derived from a
description forty times.

The division of labour that replaces it:

* **`req-offer` decides what to say.** Judgment, wording, what is in scope, what is disclosed.
* **This module decides how it is laid out.** Order, tables, figures, numbering, budgets.

The offer states **one** effort figure — the committed PERT total (ESTIMATION-METHOD.md §11.5).
Best, likely and PERT live in the workbook, one document away, where a reader who wants the spread
can find it without the whole room anchoring on a range.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt

import diagram
from common import DASH, find_internal_leaks, md, pct, rollup_figure, truncate
from docx_shell import (add_toc, fill_placeholders, pick_style, set_document_version,
                        strip_demo_sections)

TABLE_STYLES = ("Light Grid Accent 1", "Light Grid", "Table Grid")
CAPTION_STYLES = ("Geomant Caption", "Caption")


class OfferBuilder:
    """Builds one offer DOCX. Collects findings as it goes; the caller reports them all."""

    def __init__(self, artifacts, render_profile, document_profile, out_dir, version):
        self.a = artifacts
        self.rp = render_profile
        self.dp = document_profile
        self.out_dir = Path(out_dir)
        self.version = version
        self.findings = []
        self.figure_no = 0
        self.table_no = 0
        self.doc = None
        self.toc_added = False
        self.docx_cfg = (render_profile.get("docx") or {})
        self.commercial_cfg = (render_profile.get("commercial") or {})

    # ----------------------------------------------------------------- helpers

    def note(self, message):
        self.findings.append(message)

    def offer(self):
        return self.a.get("offer") or {}

    def para(self, text, style=None):
        """Write a paragraph, checking it for internal leakage and length as it goes."""
        text = (text or "").strip()
        if not text:
            return None
        leaks = find_internal_leaks(text)
        if leaks:
            raise ValueError(
                f"Refusing to write internal provenance into a client document: {leaks!r}. "
                f"The text came from an artifact and must be fixed there, not stripped here."
            )
        limit = self.docx_cfg.get("max_paragraph_words")
        if limit and len(text.split()) > limit:
            self.note(
                f"Long paragraph ({len(text.split())} words, budget {limit}): “{truncate(text, 70)}”"
            )
        return self.doc.add_paragraph(text, style=style) if style else self.doc.add_paragraph(text)

    def bullets(self, items, numbered=False):
        style = pick_style(self.doc, "List Number" if numbered else "List Bullet", "List Paragraph")
        for item in items or []:
            text = item if isinstance(item, str) else (item.get("text") or "")
            if text:
                self.para(text, style=style)

    def heading(self, text, level=1):
        self.doc.add_heading(text, level=level)

    def table(self, headers, rows, caption=None, widths=None):
        """Write a header + data table, optionally captioned and numbered."""
        rows = [r for r in rows if any(str(c or "").strip() for c in r)]
        if not rows:
            return None
        style = pick_style(self.doc, *TABLE_STYLES)
        table = self.doc.add_table(rows=1, cols=len(headers))
        if style:
            table.style = style
        for cell, header in zip(table.rows[0].cells, headers):
            cell.text = ""
            run = cell.paragraphs[0].add_run(str(header))
            run.bold = True
        for row in rows:
            cells = table.add_row().cells
            for cell, value in zip(cells, row):
                text = "" if value is None else str(value)
                leaks = find_internal_leaks(text)
                if leaks:
                    raise ValueError(f"Internal provenance in a table cell: {leaks!r}")
                cell.text = text
        if widths:
            for row in table.rows:
                for cell, width in zip(row.cells, widths):
                    cell.width = Inches(width)
        if caption and self.docx_cfg.get("caption_tables", True):
            self.table_no += 1
            self.caption(f"Table {self.table_no} — {caption}")
        return table

    def caption(self, text):
        style = pick_style(self.doc, *CAPTION_STYLES)
        paragraph = self.doc.add_paragraph(text, style=style) if style else self.doc.add_paragraph(text)
        if not style:
            for run in paragraph.runs:
                run.italic = True
        return paragraph

    def figure(self, image_path, caption):
        """Place an image scaled to the text width, with a numbered caption."""
        section = self.doc.sections[0]
        usable = (section.page_width - section.left_margin - section.right_margin) / 914400
        self.doc.add_picture(str(image_path), width=Inches(usable))
        self.doc.paragraphs[-1].alignment = 1
        if self.docx_cfg.get("caption_figures", True):
            self.figure_no += 1
            self.caption(f"Figure {self.figure_no} — {caption}")

    # ----------------------------------------------------------------- build

    def build(self, out_path):
        template = self.dp.get("template_path")
        if template and Path(template).is_file():
            self.doc = Document(str(template))
            profile = self.dp.get("profile") or {}
            report = strip_demo_sections(self.doc, profile.get("demo_sections"))
            if report["not_found"]:
                self.note(
                    "Template no longer contains these demo sections, so the profile may be stale: "
                    + ", ".join(report["not_found"])
                )
            fill_report = fill_placeholders(self.doc, self._placeholder_map(profile))
            if fill_report["unfilled"]:
                self.note("Placeholders not present in the template: " + ", ".join(fill_report["unfilled"]))
            places = set_document_version(self.doc, self.version)
            if places == 0:
                self.note("Template states no document version; none was written.")
        else:
            self.doc = Document()
            self.note(
                f"UNBRANDED build — {self.dp.get('reason') or 'no document profile resolved'}. "
                "The client will not see their branding on this document."
            )
            self._plain_cover()

        if self.docx_cfg.get("toc", True):
            self.doc.add_page_break()
            self._contents_heading()
            add_toc(self.doc)
            self.toc_added = True
            self.doc.add_page_break()

        known = {
            "introduction": self.s_introduction,
            "executive_summary": self.s_executive_summary,
            "gap_coverage": self.s_gap_coverage,
            "understanding": self.s_understanding,
            "solution": self.s_solution,
            "scope": self.s_scope,
            "delivery": self.s_delivery,
            "effort": self.s_effort,
            "assumptions_dependencies": self.s_assumptions_dependencies,
            "open_questions": self.s_open_questions,
            "commercial": self.s_commercial,
        }
        for spec in self.docx_cfg.get("sections") or []:
            sid = spec.get("id")
            renderer = known.get(sid)
            if not renderer:
                self.note(f"Render profile asks for unknown section '{sid}' — skipped.")
                continue
            before = len(self.doc.paragraphs)
            renderer(spec)
            if len(self.doc.paragraphs) == before and spec.get("required"):
                self.note(f"Required section '{sid}' produced no content — the artifacts carry none.")

        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        self.doc.save(str(out_path))
        return out_path

    def _contents_heading(self):
        """Write the "Contents" heading so that it cannot appear inside its own table of contents.

        A heading-styled paragraph is collected by the TOC field, so "Contents" lists itself as
        entry one and pushes every section number up by one. Overriding the paragraph's outline
        level looks like the fix and is not: Word normalises that override away when it re-saves
        the file during PDF export, and the entry silently comes back.

        The reliable answer is a style Word never collects. `Title` is preferred over the
        template's `TOC Heading`, because that style is often based on Heading 1 and so shares its
        numbering list: the contents page then silently consumes number 1 and every real section
        is numbered one higher than it should be. It also reads better — a contents page is not
        section 1 of the document.
        """
        style = pick_style(self.doc, "Title", "Subtitle", "TOC Heading")
        if style:
            self.doc.add_paragraph("Contents", style=style)
            return
        paragraph = self.doc.add_paragraph()
        run = paragraph.add_run("Contents")
        run.bold = True
        run.font.size = Pt(18)

    def _placeholder_map(self, profile):
        engagement = self.a.get("engagement") or {}
        offer = self.offer()
        sign_off = offer.get("sign_off") or {}
        values = {
            "project": engagement.get("project") or "",
            "client": engagement.get("client") or "",
            "artifact_title": self.docx_cfg.get("artifact_title") or "Solution offer",
            "tagline": offer.get("tagline") or engagement.get("tagline") or "",
            "generated_date": sign_off.get("date") or engagement.get("date") or "",
            "document_ref": engagement.get("document_ref") or "",
            "prepared_by": sign_off.get("prepared_by") or engagement.get("prepared_by") or "",
        }
        return {token: values.get(field, "") for token, field in (profile.get("placeholders") or {}).items()}

    def _plain_cover(self):
        engagement = self.a.get("engagement") or {}
        self.doc.add_heading(engagement.get("project") or "Solution offer", level=0)
        self.para(f"Prepared for: {engagement.get('client') or DASH}")
        sign_off = self.offer().get("sign_off") or {}
        self.para(f"Date: {sign_off.get('date') or DASH}    Version: {self.version}")

    # ----------------------------------------------------------------- sections

    def s_introduction(self, spec):
        offer = self.offer()
        intro = offer.get("introduction") or {}
        if not intro:
            return
        self.heading(spec.get("title") or "Introduction", 1)
        self.para(intro.get("text"))
        blocks = spec.get("blocks") or []
        if "basis" in blocks and intro.get("basis"):
            self.heading("Basis of this offer", 2)
            self.bullets(intro["basis"])
        if "structure" in blocks and intro.get("structure"):
            self.heading("Structure", 2)
            self.para(intro["structure"])

    def s_executive_summary(self, spec):
        text = self.offer().get("executive_summary")
        if not text:
            return
        self.heading(spec.get("title") or "Executive summary", 1)
        for paragraph in _paragraphs(text, spec.get("max_paragraphs")):
            self.para(paragraph)

    def s_gap_coverage(self, spec):
        """Client-cluster coverage — the VFRO shape, driven entirely by data.

        Rendered only when the offer carries a `client_clusters` list. A render profile asking for
        this section on an engagement without clusters gets nothing and a finding, never an
        invented table.
        """
        offer = self.offer()
        self.heading(spec.get("title") or "Objectives", 1)
        if offer.get("objectives"):
            for paragraph in _paragraphs(offer["objectives"], 4):
                self.para(paragraph)
        clusters = offer.get("client_clusters") or []
        if not clusters:
            self.note(
                "Render profile asks for a client cluster table, but offer.json carries no "
                "`client_clusters`. Section rendered without it."
            )
            return
        self.table(
            ["Ref", "Gap", "Client priority", "How the solution covers it"],
            [
                [c.get("ref"), c.get("gap"), c.get("client_priority"), c.get("coverage")]
                for c in clusters
            ],
            caption="Gap clusters and their coverage",
            widths=[0.7, 1.9, 1.3, 2.6],
        )

    def s_understanding(self, spec):
        text = self.offer().get("understanding")
        if not text:
            return
        self.heading(spec.get("title") or "Our understanding", 1)
        for paragraph in _paragraphs(text, spec.get("max_paragraphs")):
            self.para(paragraph)

    def s_solution(self, spec):
        offer = self.offer()
        solution = offer.get("solution_summary") or {}
        if not solution:
            return
        self.heading(spec.get("title") or "Solution", 1)
        blocks = spec.get("blocks") or ["principle", "diagram", "components"]

        if "principle" in blocks:
            text = solution.get("principle") or solution.get("text")
            for paragraph in _paragraphs(text, 3):
                self.para(paragraph)

        if "diagram" in blocks:
            self._solution_figure(solution)

        if "components" in blocks:
            components = self._component_rows()
            if components:
                self.heading("Components", 2)
                self.table(
                    ["Component", "What it does"],
                    components,
                    caption="Solution components",
                    widths=[2.0, 4.5],
                )
            else:
                self.note("No components available for the component list — architecture.json carries none.")

        if "data_protection" in blocks and solution.get("data_protection"):
            self.heading("Data protection", 2)
            self.para(solution["data_protection"])

    def _solution_figure(self, solution):
        architecture = self.a.get("architecture")
        if not architecture:
            self.note("No architecture.json — the solution diagram was not drawn.")
            return
        tiers, edges, report = diagram.tiers_from_architecture(architecture)
        if not tiers:
            self.note("architecture.json carries no components — the solution diagram was not drawn.")
            return
        if report["unplaced_components"]:
            self.note(
                "Components with no layer, placed in “Solution components”: "
                + ", ".join(report["unplaced_components"])
            )
        path = self.out_dir / "figures" / "solution-component-view.png"
        try:
            result = diagram.render_component_view(tiers, edges, path)
        except Exception as exc:  # noqa: BLE001 — a figure must never abort a build silently
            self.note(f"Component diagram failed to render: {exc}. The document has no Figure 1.")
            return
        if result["skipped_edges"]:
            self.note("Diagram edges naming an unknown component were skipped: " + ", ".join(result["skipped_edges"]))
        if result["default_font"]:
            self.note("No system font found; the diagram used Pillow's bitmap fallback and will look rough.")
        self.figure(path, solution.get("figure_caption") or "Solution architecture — component view")
        if solution.get("figure_note"):
            self.para(solution["figure_note"])

    def _component_rows(self):
        architecture = self.a.get("architecture") or {}
        rows = []
        for component in architecture.get("components") or []:
            if str(component.get("status", "")).lower() == "withdrawn":
                continue
            description = (
                component.get("one_liner")
                or component.get("responsibility")
                or component.get("description")
                or ""
            )
            rows.append([component.get("name") or component.get("id"), description])
        return rows

    def s_scope(self, spec):
        offer = self.offer()
        scope = offer.get("scope") or {}
        self.heading(spec.get("title") or "Scope", 1)
        blocks = spec.get("blocks") or ["in_scope", "not_in_figure", "optional", "out_of_scope"]

        if "in_scope" in blocks:
            items = scope.get("in_scope") or []
            self.heading("In scope", 2)
            if items and any(i.get("work_package") for i in items):
                self.table(
                    ["Work package", "Content"],
                    [[i.get("work_package"), i.get("text")] for i in items],
                    caption="Work packages included in this offer",
                    widths=[1.8, 4.7],
                )
            else:
                self.bullets(items)
            missing = [i for i in items if not i.get("traces_to")]
            if missing:
                raise ValueError(
                    f"{len(missing)} in-scope entries carry no `traces_to`. An offer line with "
                    "nothing behind it is a scope commitment nobody estimated — fix offer.json."
                )

        if "coverage" in blocks and scope.get("coverage"):
            self.heading("Coverage", 2)
            self.table(
                ["Requirement", "Treatment"],
                [[c.get("ref"), c.get("treatment")] for c in scope["coverage"]],
                caption="Requirement coverage",
            )

        if "not_in_figure" in blocks:
            items = scope.get("not_in_figure") or self._derive_not_in_figure()
            if items:
                self.heading("Named, and not included in the figure", 2)
                self.table(
                    ["Item", "Reason"],
                    [[i.get("text"), i.get("reason")] for i in items],
                    caption="Items named and deliberately not priced",
                    widths=[3.2, 3.3],
                )

        if "optional" in blocks and scope.get("optional"):
            self.heading("Optional additions", 2)
            self.table(
                ["Item", "Effort"],
                [[i.get("text"), md(i.get("effort_md"), unit=True)] for i in scope["optional"]],
                caption="Optional items, each priced separately and none included in the committed total",
                widths=[4.8, 1.7],
            )
            self.para(
                "Optional items are not included in the committed effort above. "
                "Each is delivered, and counted, only if it is selected."
            )

        if "out_of_scope" in blocks and scope.get("out_of_scope"):
            self.heading("Out of scope", 2)
            self.bullets(scope["out_of_scope"])

    def _derive_not_in_figure(self):
        """Fall back to the estimator's `not_estimated` list when the offer names none itself.

        The distinction matters commercially: "out of scope" says we are not doing it, while "named
        and not in the figure" says we discussed it, it is real, and it is not priced here. Losing
        the second category is how a client later believes something was included.
        """
        estimation = self.a.get("estimation") or {}
        return [
            {"text": entry.get("item") or entry.get("req"), "reason": entry.get("because")}
            for entry in estimation.get("not_estimated") or []
        ]

    def s_delivery(self, spec):
        offer = self.offer()
        phases = offer.get("delivery_plan") or []
        if not phases:
            return
        self.heading(spec.get("title") or "Delivery approach", 1)
        blocks = spec.get("blocks") or ["phases", "timeline"]

        if "phases" in blocks:
            dated = any(p.get("start_week") for p in phases)
            if dated:
                headers = ["Phase", "Weeks", "Start", "End", "Deliverable"]
                rows = [
                    [
                        p.get("name"),
                        p.get("weeks") or _span(p),
                        f"week {p['start_week']}" if p.get("start_week") else DASH,
                        f"week {p['end_week']}" if p.get("end_week") else DASH,
                        "; ".join(p.get("deliverables") or []) or p.get("deliverable") or "",
                    ]
                    for p in phases
                ]
                widths = [1.7, 0.6, 0.8, 0.8, 2.6]
            else:
                headers = ["Phase", "Duration", "Deliverable"]
                rows = [
                    [p.get("name"), p.get("duration") or DASH,
                     "; ".join(p.get("deliverables") or []) or p.get("deliverable") or ""]
                    for p in phases
                ]
                widths = [1.8, 1.2, 3.5]
                self.note(
                    "Delivery phases carry no week numbers, so no timeline chart was drawn. "
                    "Add `start_week`/`end_week` in offer.json to get one."
                )
            self.table(headers, rows, caption="Delivery phases", widths=widths)

        if "timeline" in blocks:
            self._timeline_figure(phases, offer)

    def _timeline_figure(self, phases, offer):
        drawable = [
            {
                "name": p.get("name"),
                "start": p.get("start_week"),
                "end": p.get("end_week"),
                "effort_md": p.get("effort_md"),
            }
            for p in phases
            if p.get("start_week") and p.get("end_week")
        ]
        if not drawable:
            return
        path = self.out_dir / "figures" / "delivery-timeline.png"
        try:
            diagram.render_timeline(drawable, path)
        except Exception as exc:  # noqa: BLE001
            self.note(f"Timeline chart failed to render: {exc}.")
            return
        self.heading("Timeline", 2)
        self.figure(path, "Indicative delivery timeline")
        timeline = offer.get("timeline") or {}
        total = timeline.get("total_weeks") or max(p["end"] for p in drawable)
        self.para(
            timeline.get("note")
            or f"The indicative end-to-end duration is {total} weeks from project start. "
            "A firm plan is agreed at kick-off, once the client dependencies in this document are met."
        )

    def s_effort(self, spec):
        estimation = self.a.get("estimation")
        if not estimation:
            self.note("No estimation.json — the offer states no effort.")
            return
        rollup = estimation.get("rollup") or {}
        committed = rollup_figure(rollup, "committed")
        if committed is None:
            self.note("estimation.json carries no committed total — the effort section was skipped.")
            return

        self.heading(spec.get("title") or "Effort", 1)
        blocks = spec.get("blocks") or ["headline", "by_phase", "optional_effort", "support"]

        contingency = rollup.get("contingency") or {}

        if "headline" in blocks:
            self.para("The committed effort to deliver the scope in this document is:")
            paragraph = self.doc.add_paragraph()
            run = paragraph.add_run(md(committed, unit=True, whole=True))
            run.bold = True
            if contingency.get("percent"):
                self.para(
                    f"The figure includes a {pct(contingency['percent'])} contingency "
                    f"({md(rollup_figure(rollup, 'contingency.amount'), unit=True, whole=True)}) "
                    "derived from the risks named in this document, and covers every work package "
                    "listed above, including design, testing, documentation, deployment and "
                    "project management."
                )
            else:
                self.para(
                    "The figure covers every work package listed above, including design, testing, "
                    "documentation, deployment and project management."
                )

        if "by_phase" in blocks:
            # The table must add up. A phase breakdown that sums to the baseline under a row
            # labelled "total committed" is the misreading ESTIMATION-METHOD.md §11.1 exists to
            # prevent, so contingency gets its own visible row between the two.
            rows = [
                [p.get("name") or p.get("phase"),
                 md(p.get("pert") if p.get("pert") is not None else p.get("likely"), whole=True)]
                for p in rollup.get("by_phase") or []
                if (p.get("scope_tier") or "baseline") == "baseline"
            ]
            if rows:
                baseline = rollup_figure(rollup, "baseline")
                amount = rollup_figure(rollup, "contingency.amount")
                if baseline is not None:
                    rows.append(["Baseline, before contingency", md(baseline, whole=True)])
                if amount:
                    rows.append([f"+ Contingency ({pct(contingency.get('percent'))})",
                                 md(amount, whole=True)])
                buffer_amount = rollup_figure(rollup, "buffer.amount")
                if buffer_amount:
                    rows.append(["+ Buffer", md(buffer_amount, whole=True)])
                rows.append(["= Total committed", md(committed, whole=True)])
                self.table(["Phase", "Man-days"], rows,
                           caption="Effort by delivery phase", widths=[4.8, 1.7])
                self.para(
                    "Phase figures are the phase shares of the baseline, before contingency. "
                    "The commitment is the total, not an individual phase."
                )
            else:
                self.note("estimation.json has no by_phase rollup — no phase breakdown was written.")

        if "optional_effort" in blocks:
            optional = rollup_figure(rollup, "optional")
            if optional:
                self.table(
                    ["Item", "Man-days"],
                    [["Optional scope, priced separately", md(optional, whole=True)]],
                    caption="Optional items, not included in the committed total",
                    widths=[4.8, 1.7],
                )

        if "support" in blocks:
            support = (self.offer().get("commercial") or {}).get("support_md_per_year")
            if support:
                self.table(
                    ["Item", "Man-days per year"],
                    [["Annual support and maintenance", md(support, whole=True)]],
                    caption="Support and maintenance, separate from the build total",
                    widths=[4.8, 1.7],
                )

    def s_assumptions_dependencies(self, spec):
        offer = self.offer()
        blocks = spec.get("blocks") or ["assumptions", "client_dependencies", "risks"]
        assumptions = offer.get("assumptions") or []
        dependencies = offer.get("client_dependencies") or []
        risks = self._risk_rows()
        if not (assumptions or dependencies or risks):
            return
        self.heading(spec.get("title") or "Assumptions, dependencies and risks", 1)

        if "assumptions" in blocks and assumptions:
            self.heading("Assumptions", 2)
            self.table(
                ["Assumption", "If it proves wrong"],
                [[a.get("text"), a.get("consequence_if_wrong") or DASH] for a in assumptions],
                caption="Assumptions this offer rests on",
                widths=[3.6, 2.9],
            )

        if "client_dependencies" in blocks and dependencies:
            self.heading("Client dependencies", 2)
            self.table(
                ["What is needed", "By when"],
                [[d.get("text"), d.get("needed_by") or DASH] for d in dependencies],
                caption="Dependencies on the client",
                widths=[4.4, 2.1],
            )

        if "risks" in blocks and risks:
            self.heading("Risks and how they are managed", 2)
            self.table(
                ["Risk", "Impact", "How it is managed"],
                risks,
                caption="Risks shaping the commercial terms",
                widths=[2.6, 0.9, 3.0],
            )

    def _risk_rows(self):
        """Join the offer's disclosed risk IDs against the risk register.

        A disclosed ID with no register entry is reported and dropped. Writing the bare ID into a
        client document, which is the tempting fallback, tells the reader nothing and advertises
        that something is missing.
        """
        register = self.a.get("risk_register") or {}
        by_id = {r.get("id"): r for r in register.get("risks") or []}
        rows, orphans = [], []
        for rid in self.offer().get("risks_disclosed") or []:
            risk = by_id.get(rid)
            if not risk:
                orphans.append(rid)
                continue
            rows.append([
                risk.get("text") or risk.get("title"),
                (risk.get("impact") or DASH).capitalize() if isinstance(risk.get("impact"), str) else DASH,
                risk.get("treatment") or risk.get("mitigation") or DASH,
            ])
        if orphans:
            self.note("Disclosed risks with no entry in risk-register.json, omitted: " + ", ".join(orphans))
        return rows

    def s_open_questions(self, spec):
        questions = self.offer().get("open_questions") or []
        if not questions:
            return
        self.heading(spec.get("title") or "Questions to confirm before start", 1)
        self.table(
            ["Question", "What it affects"],
            [[q.get("text"), q.get("affects") or DASH] for q in questions],
            caption="Open questions",
            widths=[3.9, 2.6],
        )

    def s_commercial(self, spec):
        offer = self.offer()
        commercial = offer.get("commercial") or {}
        self.heading(spec.get("title") or "Commercial terms", 1)

        if self.commercial_cfg.get("forbid_currency") and commercial.get("currency"):
            raise ValueError(
                f"Render profile '{self.rp['_resolved']['name']}' forbids a currency in the offer, "
                f"but offer.json sets currency '{commercial['currency']}'. This account is priced "
                "under a frame agreement; resolve it in the artifact, not here."
            )

        terms = list(self.commercial_cfg.get("standard_terms") or [])
        sign_off = offer.get("sign_off") or {}
        if sign_off.get("valid_until"):
            terms.insert(0, f"This offer is valid until {sign_off['valid_until']}.")
        elif commercial.get("validity_days"):
            terms.insert(0, f"This offer is valid for {commercial['validity_days']} days from its date.")
        if commercial.get("basis") == "effort-only" and not self.commercial_cfg.get("standard_terms"):
            terms.append(
                "This offer states effort only. No rate card was applied, so no price, day rate or "
                "currency appears in it. Pricing is a separate commercial discussion."
            )
        terms.extend(commercial.get("terms") or [])
        self.bullets(terms)
        if commercial.get("note"):
            self.para(commercial["note"])


def _paragraphs(text, limit=None):
    """Split a text block into paragraphs, honouring a section's paragraph budget."""
    if not text:
        return []
    parts = [p.strip() for p in str(text).split("\n\n") if p.strip()]
    if not parts:
        return []
    if limit and len(parts) > limit:
        return parts[:limit]
    return parts


def _span(phase):
    start, end = phase.get("start_week"), phase.get("end_week")
    if start and end:
        return end - start + 1
    return DASH
